; PlatformIO Configuration File for TapTrack Nodes
; --------------------------------------------------
; Common configuration settings shared by all environments
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3

; Titik 1: Absensi Node Environment
[env:absensi]
build_flags = -D NODE_ABSENSI

; Titik 2: Akses Pintu Node Environment
[env:akses_pintu]
build_flags = -D NODE_AKSES_PINTU

; Titik 3: Canteen Node Environment
[env:kantin]
build_flags = -D NODE_KANTIN
